### ISSUE TITLE
GH stats are double counted at project level

### ISSUE THREAD

**Issue by pmonks** [finos/metadata-tool#10]
When GitHub stats (especially watchers and stars) are accumulated from the repository level to the project level, there is some double (or triple, quadruple, etc.) counting going.  See [this code](https://github.com/finos/metadata-tool/blob/master/src/metadata_tool/tools/generators.clj#L86) for example.

What should happen is that any time any one user watches any number of repositories in a project, they're only counted once.

**Comment by maoo** [comment]
Marking this bug as low priority, since we're working with LF on the FINOS Landscape page, see https://github.com/finos/open-developer-platform/issues/53

**Comment by maoo** [comment]
Closing issue, as we moved to landscape.finos.org
