### ISSUE TITLE
set-exit-code doesn't doesn't validate new exit code values

### ISSUE THREAD

**Issue by pmonks** [finos/metadata-tool#26]
The `set-exit-code` fn in the `exit-code` ns should validate `new-exit-code` before swapping the value in the private atom.

**Comment by pmonks** [comment]
This might be done between [lines 24 and 25 of that ns](https://github.com/finos/metadata-tool/blob/master/src/metadata_tool/exit_code.clj#L24-L25) via a condition such as `(if (integer? new-exit-code)`

**Comment by maoo** [comment]
Done, TY!
