### ISSUE TITLE
Automatically invite people to github.com/orgs/finos/people when CLA covered

### ISSUE THREAD

**Issue by maoo** [finos/metadata-tool#54]
In order to maximise the amount of people signed on https://github.com/orgs/finos/people , while enforcing CLA signature, metadata-tool can embed the logic of inviting GitHub users as soon as they are covered by CLA.

Code is already implemented on https://github.com/finos/metadata-tool/pull/53 and delivers the command `invite-clas-to-finos-org`.

Rollout is tracked on https://github.com/finos/open-developer-platform/issues/114

**Comment by mcleo-d** [comment]
Related to #114

**Comment by mcleo-d** [comment]
Announce email being created by @mcleo-d and @maoo in the following restricted Google Doc ...
* https://docs.google.com/document/d/1QRzcDFKRXesFTeLZ6hUUGSKlUI8ff-SnRQv9lwCKCHQ/edit?usp=sharing
