### ISSUE TITLE
Extend projects-metadata definitions to include Special Interest Group `SIG` Type

### ISSUE THREAD

**Issue by mcleo-d** [finos/metadata-tool#61]
## Feature Request

Within GitHub Issue https://github.com/finos/metadata/issues/648#issuecomment-706807544 an automated script is being used to run a report that extracts FINOS project maintainers. However, this script currently excludes FINOS projects of type `SIG`.  

## Special Interest Group Type

```
  "type"             : "SIG"
```

## Including SIG Type

This issue requests `metadata-tool` is extended to include type `SIG`, potentially included in the code block below, or potentially as the new definition `defn sigs-metadata`  

https://github.com/finos/metadata-tool/blob/d673b179f5d0f4bbc6fe47451b394c6f768d2d06/src/metadata_tool/sources/metadata.clj#L387-L390

## Potential SIG Definition

```
(defn sigs-metadata
  "A seq containing the metadata of all activities of type SIG, regardless of program."
  []
  (filter #(= (:type %) "SIG") (activities-metadata)))
```

## The Ask

- [ ] Before a pull request is raised, it would be good to discuss and agree the right approach / desired outcome with @maoo and @mcleo-d.
- [ ] Does the addition of the `SIG` type potentially lead to unforeseen consequences when reporting against FINOS projects?

**Comment by maoo** [comment]
Hi @mcleo-d , thanks for raising this bug! As you noticed, after introducing the new `SIG` type, I forgot to change this logic.

I just pushed a commit to dev to address the bug, which is basically adding a new function that returns SIGs and projects, and use this function for the github meetings roster logic; this way no other logic is impacted.

If you're curious, you can check code on https://github.com/finos/metadata-tool/commit/1b893b0396b56463f2b05f018d4a1f9df133ec66 , should be quite straight-forward.

**Comment by mcleo-d** [comment]
Thanks for the opportunity to review. I've now closed the issue.
